name = "backend"
compatibility_date = "2024-08-02"

 [vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMDg3NmIyZDgtNjI0OC00MTU0LTg5MTEtYmRmMDNkY2ZlN2EyIiwidGVuYW50X2lkIjoiODNjZDI5MzdjODk3ZjQxNmViYjMyZDhkYTA0NDVmOGQyZDNlN2MxZGNhMGZjYzlkMTZhY2M3ZWNhYjA3NjNlNiIsImludGVybmFsX3NlY3JldCI6ImRkNWMxZWQzLWE2NGYtNDgwZS05ZTc3LTM4NjhkZWU0YjZlMiJ9.DXyC9ntD4u-tweN16JhMNuBNAinXGCxJlQzobABNpQ8"


